spring:
  #配置redis数据库信息
  data:
    redis:
      database: 0
      password: 123321
      host: localhost
      port: 6379
  #配置数据库信息
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aiProject


#配置数据库驼峰转换
mybatis:
  configuration:
    map-underscore-to-camel-case: true


jwt_key: 7nS8V2gP5dF9kL3zX1bN6mR4tY7uI0oE2wQ5eR8tY